# Settings in the [build] context are global and are applied to all contexts 
# unless otherwise overridden by more specific contexts.  
[build]
  # Directory to change to before starting a build. 
  # This is where we will look for package.json/.nvmrc/etc.
  base = "nuxt/"


# Production context: all deploys from the Production branch set in your site's 
# deploy contexts will inherit these settings.
[context.production]
  publish = "nuxt/dist"
  command = "yarn generate"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to 
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are 
# PER-DEPLOY.

# A basic redirect rule
[[redirects]]
  from = "/ans"
  to = "/answer/dpst-natthawut-mc1"
